# Generated by Django 4.2 on 2023-04-15 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poliza_Asegurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Asegurado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.asegurado')),
            ],
        ),
        migrations.AlterField(
            model_name='poliza',
            name='Id_Asegurado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.poliza_asegurado'),
        ),
    ]
