# Generated by Django 4.2 on 2023-04-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_poliza_asegurado_alter_poliza_id_asegurado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
