# Generated by Django 4.2 on 2023-04-17 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_agente_email_alter_cliente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aseguradora', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='poliza',
            old_name='Estado_Poliza',
            new_name='Id_Estado_Poliza',
        ),
        migrations.RenameField(
            model_name='poliza',
            old_name='Tipo_Poliza',
            new_name='Id_Tipo_Poliza',
        ),
        migrations.RemoveField(
            model_name='poliza',
            name='Aseguradora',
        ),
        migrations.AddField(
            model_name='poliza',
            name='Id_Aseguradora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.aseguradora'),
            preserve_default=False,
        ),
    ]
